Traceback (most recent call last):
  File "/home/grabow/anaconda3/envs/jb/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/grabow/anaconda3/envs/jb/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/grabow/anaconda3/envs/jb/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/grabow/anaconda3/envs/jb/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/grabow/anaconda3/envs/jb/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/grabow/anaconda3/envs/jb/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/grabow/anaconda3/envs/jb/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/grabow/anaconda3/envs/jb/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Download real time 
url = 'https://data.geobasis-bb.de/geofachdaten/Wasser/Grundwasser/gw_basis_mn.zip'
local_path = 'tmp/'

r = requests.get(url)
z = zipfile.ZipFile(io.BytesIO(r.content))
z.extractall(path=local_path) # extract to folder
filenames = [y for y in sorted(z.namelist()) for ending in ['dbf', 'prj', 'shp', 'shx'] if y.endswith(ending)] 

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 5>[0;34m()[0m
[1;32m      2[0m url [38;5;241m=[39m [38;5;124m'[39m[38;5;124mhttps://data.geobasis-bb.de/geofachdaten/Wasser/Grundwasser/gw_basis_mn.zip[39m[38;5;124m'[39m
[1;32m      3[0m local_path [38;5;241m=[39m [38;5;124m'[39m[38;5;124mtmp/[39m[38;5;124m'[39m
[0;32m----> 5[0m r [38;5;241m=[39m [43mrequests[49m[38;5;241m.[39mget(url)
[1;32m      6[0m z [38;5;241m=[39m zipfile[38;5;241m.[39mZipFile(io[38;5;241m.[39mBytesIO(r[38;5;241m.[39mcontent))
[1;32m      7[0m z[38;5;241m.[39mextractall(path[38;5;241m=[39mlocal_path) [38;5;66;03m# extract to folder[39;00m

[0;31mNameError[0m: name 'requests' is not defined
NameError: name 'requests' is not defined

